### PR TITLE
Add arm files: arm_init.c, filter_neon_intrinsics.c, filter_neon.S

### PR DESCRIPTION
**Pull request by camerbam**

### CODE REVIEW

**Comment by camerbam** [comment]
I apparently missed a few steps in my testing, I would hold off on looking at this pull till I check a few more things...

**Comment by camerbam** [comment]
This pull is now ready.

**Comment by smanders** [comment]
I'm not planning to merge this pull... wxcmake is Windows-specific and always will be (since future releases of wx have cmake support and when we move to a version that has cmake support wxcmake will become obsolete and instead we will patch their cmake, if necessary).

The thing that convinced me *not* to merge this: I checked out the v3.1.1 tag, did a submodule init/update to get the png submodule, and opened build/msw/wx_vc15.sln (which wxcmake tries to mimic) and the arm source is of course not in the wx_wxpng.vcxproj...

Please let me know @cameronfrandsen if you see this pull as necessary or convenient in some way that I'm not recognizing

**Comment by smanders** [comment]
closing (almost a year later...) for reasons stated above

**Pull request closed without merging**
